kafka:
  container_name: kafka
  image: spotify/kafka:latest
  ports:
    - "2181:2181"
    - "9092:9092"
  environment:
    ADVERTISED_HOST: 192.168.99.100
    ADVERTISED_PORT: 9092

cassandra:
  container_name: cassandra
  image: spotify/cassandra:latest
  ports:
    - "9160:9160"
    - "9042:9042"

producer:
  container_name: producer
  image: meierc/sid-mesos-kafka-producer:latest
  environment:
    PRODUCER_HOSTS: 192.168.99.100:9092

consumer:
  container_name: consumer
  image: meierc/sid-mesos-kafka-consumer:latest
  ports:
    - "8080:8080"
  environment:
    CONSUMER_HOSTS: 192.168.99.100:2181

grid:
  container_name: grid
  image: meierc/sid-mesos-cassandra-grid:latest
  ports:
    - "8081:8080"
  environment:
    CASSANDRA_HOST: 192.168.99.100
